apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
spec:
  workspaces:
  - name: messages
  steps:
    - name: say-hello
      image: registry.access.redhat.com/ubi8/ubi
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo 'Doing a new build'
          pwd
          ls -l
          echo 'volume mount check' > /source-pvc/bar
          echo 'the end'
